<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net80</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Luax.Interpreter\Luax.Interpreter.csproj" />
    <ProjectReference Include="..\Luax.Parser\Luax.Parser.csproj" />
    <ProjectReference Include="..\LuaX\LuaX.csproj" />
  </ItemGroup>
</Project>
